### ISSUE TITLE
Model: Attempted to detach a parent that was not attached to us

### ISSUE THREAD

**Issue by sebbert** [fusetools/fuselibs-public#958] opened 2018-01-22 10:19 UTC
Not linking the test case here as this came from a user, but we hit another case of detaching a node that is not our child.

**Comment by mortoray** [comment] 2018-01-25 04:48
Probably a duplicate of https://github.com/fusetools/fuselibs-public/issues/922

**Closed** 2018-01-31 12:02 UTC
