### ISSUE TITLE
iOS: Fuse apps are always in portrait mode in v.1.4.x

### ISSUE THREAD

**Issue by Tapped** [fusetools/fuselibs-public#722] opened 2017-11-09 14:21 UTC
The issue is not reproducible in v.1.3.x

### Steps to reproduce
1. `fuse create example ScreenOrientationTest`
2. `uno build -t=ios -r ScreenOrientationTest`
3. Try rotating the device
4. Also, make sure device orientation lock is disabled 

![](https://scache.vzw.com/kb/images/common/apple/menu/control_center_main_up.jpg)

**Comment by Tapped** [comment] 2017-11-09 14:23
By the way, the problem is reproducible in the simulator as well.

**Comment by Tapped** [comment] 2017-11-09 14:28
Actually this is 1.4.0-rc4-master-a7eab71 so it may not have been released yet.

**Comment by kusma** [comment] 2017-11-09 14:30
Duplicate of #685, which was already fixed.

**Closed by kusma** 2017-11-09 14:30 UTC
