### ISSUE TITLE
Curve does not draw a line when it should

### ISSUE THREAD

**Issue by eksperts** [fusetools/fuselibs-public#468] opened 2017-09-19 08:10 UTC
[Reported on community](https://www.fusetools.com/community/forums/bug_reports/curve_dont_draw_line).

Fuse 1.2.1 build 13974, macOS.

Consider the following code:
```
<App>
    <Curve StrokeWidth="5" Width="100" Height="100" StrokeColor="#000" Style="Straight">
        <CurvePoint At="0,0" />
        <CurvePoint At="0,1" />
    </Curve>
</App>
```
It should draw a 100pt tall vertical line, but it's not there.
Adding a third point to the `Curve` makes the line appear:
```
<App>
    <Curve StrokeWidth="5" Width="100" Height="100" StrokeColor="#000" Style="Straight">
        <CurvePoint At="0,0" />
        <CurvePoint At="0,1" />
        <CurvePoint At="1,1" />
    </Curve>
</App>
```
Drawing a line at 45 degrees works just fine:
```
<App>
    <Curve StrokeWidth="5" Width="100" Height="100" StrokeColor="#000" Style="Straight">
        <CurvePoint At="0,0" />
        <CurvePoint At="1,1" />
    </Curve>
</App>
```

**Comment by fusebuild** [comment] 2017-09-19 08:12
The forum thread [Curve don't draw line](https://www.fusetools.com/community/forums/bug_reports/curve_dont_draw_line) posted by SvenWS was linked to this issue.

**Comment by kusma** [comment] 2017-09-19 08:25
This is a duplicate of #270

**Closed by kusma** 2017-09-19 08:25 UTC
