### ISSUE TITLE
Setting MaxLength on Text element only works the first time

### ISSUE THREAD

**Issue by anettegj** [fusetools/fuselibs-public#343] opened 2017-08-07 10:58 UTC
#### How to reproduce
1. Create a new project 
1. Add a text element
1. Type in a string of some length
1. Open the ux-file
1. Add MaxLength to the Text-element and give it the value 1
1. Observe that only the first character of the text is now displayed in the preview.
1. Change MaxLength to 10 in the ux-file
#### Change is not reflected in the preview which still only shows one character of the text value
The same thing can be reproduced changing MaxLength from the inspector in Fuse Studio

**Comment by kusma** [comment] 2017-08-07 11:34
@anettegj: This sounds like a duplicate of https://www.fusetools.com/community/forums/bug_reports/bug_with_maxlength_in_text_component / [fusetools/fuselibs#4155]. Long story short; MaxLength was never intended to work on Text-elements in the first place. It's not supposed to be there, and will be removed. We're not planning on fixing anything with it either.

**Closed by kusma** 2017-08-07 11:34 UTC
