### ISSUE TITLE
Model: Exception in promises

### ISSUE THREAD

**Issue by drslem** [fusetools/fuselibs-public#611] opened 2017-10-19 09:35 UTC
User testing feedback:
If an uncaught exception is thrown in a Promise / promise callback, all promise callbacks from then on, until app restart, will be ignored. 

Additionally, this happens silently in the background (no stack trace and the app keeps running), so the issue can cause a lot of frustration

**Comment by kusma** [comment] 2017-10-19 09:37
I think this is a bug in Uno in that case. That's where the Promise code lives.

**Comment by sebbert** [comment] 2017-11-13 10:26
Fixed in https://github.com/fusetools/fuselibs-public/pull/723

This was caused by zone.js catching all errors, and then attempting to report them using `console.error`. Since we did not implement `console.error`, this would again throw an error that zone.js did not expect, thus breaking all subsequent promises.

**Closed by sebbert** 2017-11-13 10:26 UTC
