### ISSUE TITLE
Crash in preview mode after onValueChanged actions using <DatePicker /> 

### ISSUE THREAD

**Issue by ianychoi** [fusetools/fuselibs-public#953] opened 2018-01-19 02:18 UTC
Fuse version 1.5.0 (build 15046)

Problem: Example code in https://www.fusetools.com/docs/fuse/controls/datepicker does not work in preview mode (both preview app and preview mode using cables) for Android and iOS. When users change some date by clicking a different date in native iOS and Android datepickers, then the app crashes. Interestingly, exporting to apps as apk, or ipa works fine without any crashes.

- iOS call stack (preview mode)
```
Thread 1 Queue : com.apple.main-thread (serial)
#0	0x0000000100092fc0 in uBase::AtomicDecrement(int*) [inlined] at /usr/local/share/uno/Packages/UnoCore/1.4.3/prebuilt/iOS/include/uBase/Atomic.h:24
#1	0x0000000100092fb8 in uRelease(uObject*) at /Users/ian/Downloads/TestApp/build/iOS/Preview/src/Uno/Memory.cpp:311
#2	0x0000000100092cd0 in uPopAutoReleasePool(uThreadData*) at /Users/ian/Downloads/TestApp/build/iOS/Preview/src/Uno/Memory.cpp:189
#3	0x0000000100092d88 in uForeignPool::~uForeignPool() at /Users/ian/Downloads/TestApp/build/iOS/Preview/src/Uno/Memory.cpp:224
#4	0x00000001002c1e58 in ::___ZZN1g4Fuse8Controls6Native3iOS14UIControlEvent6CreateEPNS_4ObjC6ObjectEP9uDelegateiENK3$_1clEPU19objcproto9UnoObject11objc_object_block_invoke(id, id) at /Users/ian/Downloads/TestApp/build/iOS/Preview/src/Fuse.Controls.Native.iOS.UIControlEvent.mm:145
#5	0x000000010009e538 in ::-[UIControlEventHandler action:forEvent:](id, UIEvent *) at /Users/ian/Downloads/TestApp/build/iOS/Preview/src/iOS/Helpers.mm:156
#6	0x000000018b449c54 in -[UIApplication sendAction:to:from:forEvent:] ()
#7	0x000000018b449bd4 in -[UIControl sendAction:to:forEvent:] ()
#8	0x000000018b434148 in -[UIControl _sendActionsForEvents:withEvent:] ()
#9	0x000000018bd41428 in -[_UIDatePickerView pickerView:didSelectRow:inComponent:] ()
#10	0x000000018b684fe4 in -[UIPickerView _sendSelectionChangedForComponent:notify:] ()
#11	0x000000018b685218 in -[UIPickerView _sendSelectionChangedFromTable:notify:] ()
#12	0x000000018bbbf174 in -[UIPickerTableView _scrollingFinished] ()
#13	0x000000018bbbf34c in -[UIPickerTableView scrollViewDidEndDecelerating:] ()
#14	0x000000018b727198 in -[UIScrollView(UIScrollViewInternal) _scrollViewDidEndDeceleratingForDelegate] ()
#15	0x000000018b5b9d00 in -[UIScrollView(UIScrollViewInternal) _stopScrollDecelerationNotify:] ()
#16	0x000000018b5b97a0 in -[UIScrollView _smoothScrollWithUpdateTime:] ()
#17	0x000000018b5b8da8 in -[UIScrollView _smoothScrollDisplayLink:] ()
#18	0x00000001019f84fc in __clang_call_terminate ()
#19	0x00000001884f55dc in CA::Display::DisplayLinkItem::dispatch(unsigned long long) ()
#20	0x00000001884f548c in CA::Display::DisplayLink::dispatch_items(unsigned long long, unsigned long long, unsigned long long) ()
#21	0x000000018554fb9c in IODispatchCalloutFromCFMessage ()
#22	0x0000000185279960 in __CFMachPortPerform ()
#23	0x0000000185291ae4 in __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ ()
#24	0x0000000185291284 in __CFRunLoopDoSource1 ()
#25	0x000000018528ed98 in __CFRunLoopRun ()
#26	0x00000001851beda4 in CFRunLoopRunSpecific ()
#27	0x0000000186c29074 in GSEventRunModal ()
#28	0x000000018b479c9c in UIApplicationMain ()
#29	0x000000010009b3bc in main at /Users/ian/Downloads/TestApp/build/iOS/Preview/src/Uno-iOS/Main.mm:14
#30	0x00000001841cd59c in start ()
```

- Android adb log (preview mode)
```
$ fuse preview -t=android
Fuse 1.5.0 (build 15046)
Starting preview for //Users/ian/Downloads/TestApp/TestApp.unoproj, target Android
Configuring (2.0 s)
Compiling syntax tree (1.3 s)
Generating code and dataFontconfig warning: no <cachedir> elements found. Check configuration.
Fontconfig warning: adding <cachedir>~/Library/Caches/com.xamarin.fontconfig</cachedir>
Fontconfig warning: adding <cachedir prefix="xdg">fontconfig</cachedir>
 (5.6 s)
Building Android app (18.0 s)

Build completed in 27.04 seconds
Installing APK on 1 device(s)
Launching activity 'TestApp'
Running logcat on 80b84a5e
01-19 11:04:06.282 15800 15800 E Zygote  : v2
01-19 11:04:06.282 15800 15800 I libpersona: KNOX_SDCARD checking this for 10460
01-19 11:04:06.282 15800 15800 I libpersona: KNOX_SDCARD not a persona
01-19 11:04:06.292 15800 15800 I SELinux : Function: selinux_compare_spd_ram, index[1], SPD-policy is existed. and_ver=SEPF_SM-G900S_5.0-1 ver=47
01-19 11:04:06.292 15800 15800 W SELinux : Function: selinux_compare_spd_ram, index[1], priority [2], priority version is VE=SEPF_SECMOBILE_6.0.1_0032
01-19 11:04:06.292 15800 15800 E Zygote  : accessInfo : 0
01-19 11:04:06.292 15800 15800 W SELinux : SELinux: seapp_context_lookup: seinfo=default, level=s0:c512,c768, pkgname=com.apps.testapp 
01-19 11:04:06.292 15800 15800 I art     : Late-enabling -Xcheck:jni
01-19 11:04:06.292   770  1700 I ActivityManager: Start proc 15800:com.apps.testapp/u0a460 for activity com.apps.testapp/.TestApp
01-19 11:04:06.312 15800 15800 D TimaKeyStoreProvider: TimaSignature is unavailable
01-19 11:04:06.312 15800 15800 D ActivityThread: Added TimaKeyStore provider
01-19 11:04:06.342 15800 15800 W ResourcesManager: getTopLevelResources: /data/app/com.apps.testapp-1/base.apk / 1.0 running in com.apps.testapp rsrc of package null
01-19 11:04:06.362 15800 15800 D TestApp : SDK: 23
01-19 11:04:06.432 15800 15800 W ResourcesManager: getTopLevelResources: /data/app/com.apps.testapp-1/base.apk / 1.0 running in com.apps.testapp rsrc of package null
01-19 11:04:06.442 15800 15800 I Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: EGL 1.4 QUALCOMM build:  (Ia10634f51b)
01-19 11:04:06.442 15800 15800 I Adreno-EGL: OpenGL ES Shader Compiler Version: E031.29.00.00
01-19 11:04:06.442 15800 15800 I Adreno-EGL: Build Date: 01/28/16 Thu
01-19 11:04:06.442 15800 15800 I Adreno-EGL: Local Branch: ss
01-19 11:04:06.442 15800 15800 I Adreno-EGL: Remote Branch: 
01-19 11:04:06.442 15800 15800 I Adreno-EGL: Local Patches: 
01-19 11:04:06.442 15800 15800 I Adreno-EGL: Reconstruct Branch: 
01-19 11:04:06.452 15800 15800 D libEGL  : eglInitialize EGLDisplay = 0xbe930bec
01-19 11:04:06.782 15800 15800 D ViewRootImpl: #1 mView = com.android.internal.policy.PhoneWindow$DecorView{8078ac0 I.E...... R.....I. 0,0-0,0}
01-19 11:04:06.782 15800 15854 D OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
01-19 11:04:06.782 15800 15800 D SecWifiDisplayUtil: Metadata value : none
01-19 11:04:06.862 15800 15854 D libEGL  : eglInitialize EGLDisplay = 0x9e53f7c4
01-19 11:04:06.862 15800 15854 I OpenGLRenderer: Initialized EGL, version 1.4
01-19 11:04:06.892 15800 15800 W DisplayListCanvas: DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
01-19 11:04:06.892 15800 15800 V ActivityThread: updateVisibility : ActivityRecord{5eb7f3e token=android.os.BinderProxy@88fa443 {com.apps.testapp/com.apps.testapp.TestApp}} show : true
01-19 11:04:06.912 15800 15800 D ViewRootImpl: MSG_RESIZED_REPORT: ci=Rect(0, 72 - 0, 0) vi=Rect(0, 72 - 0, 0) or=1
01-19 11:04:06.912 15800 15800 I Timeline: Timeline: Activity_idle id: android.os.BinderProxy@88fa443 time:727516
01-19 11:04:10.092 15800 16145 D TestApp : someDate changed: "2007-02-14T00:00:00.000Z"
01-19 11:04:10.142 15800 15800 D AbsListView: Get MotionRecognitionManager
01-19 11:04:10.152 15800 15800 E MotionRecognitionManager: mSContextService = android.hardware.scontext.ISContextService$Stub$Proxy@793a0fa
01-19 11:04:10.152 15800 15800 E MotionRecognitionManager: motionService = com.samsung.android.motion.IMotionRecognitionService$Stub$Proxy@43e6ab
01-19 11:04:10.152 15800 15800 E MotionRecognitionManager: motionService = com.samsung.android.motion.IMotionRecognitionService$Stub$Proxy@43e6ab
01-19 11:04:10.202 15800 15800 I Choreographer: Skipped 38 frames!  The application may be doing too much work on its main thread.
01-19 11:04:10.662 15800 15800 I ViewPager: Current page list:
01-19 11:04:10.662 15800 15800 I ViewPager: #0: page 684
01-19 11:04:10.662 15800 15800 I ViewPager: #1: page 685
01-19 11:04:10.662 15800 15800 I ViewPager: #2: page 686
01-19 11:04:10.662 15800 15800 I ViewPager: Current page list:
01-19 11:04:10.662 15800 15800 I ViewPager: #0: page 684
01-19 11:04:10.662 15800 15800 I ViewPager: #1: page 685
01-19 11:04:10.662 15800 15800 I ViewPager: #2: page 686
01-19 11:04:10.922   770  1898 D InputDispatcher: Focus entered window: 15800
01-19 11:04:11.102 15800 15800 I Timeline: Timeline: Activity_idle id: android.os.BinderProxy@88fa443 time:731704
01-19 11:04:13.322 15800 15800 D ViewRootImpl: ViewPostImeInputStage processPointer 0
01-19 11:04:13.322 15800 15800 V ViewPager: Down at 643.0,497.0 mIsBeingDragged=falsemIsUnableToDrag=false
01-19 11:04:13.322   770  1261 I InputDispatcher: Delivering touch to (15800): action: 0x0, toolType: 1
01-19 11:04:13.352 15800 15800 V ViewPager: Moved x to 641.92053,497.0 diff=1.0794678,0.0
01-19 11:04:13.352 15800 15800 V ViewPager: Moved x to 640.5,497.0 diff=2.5,0.0
01-19 11:04:13.442 15800 15800 V ViewPager: Moved x to 641.0,497.0 diff=2.0,0.0
01-19 11:04:13.452   770  1261 I InputDispatcher: Delivering touch to (15800): action: 0x1, toolType: 1
01-19 11:04:13.452 15800 15800 V ViewPager: Moved x to 643.0,498.0 diff=0.0,1.0
01-19 11:04:13.452 15800 15800 D ViewRootImpl: ViewPostImeInputStage processPointer 1
01-19 11:04:13.452 15800 15800 V ViewPager: Intercept done!
01-19 11:04:13.512 15800 15800 W         : Unable to open '/system/framework/com.qti.location.sdk.jar': No such file or directory
01-19 11:04:13.512 15800 15800 W art     : Failed to open zip archive '/system/framework/com.qti.location.sdk.jar': I/O Error
01-19 11:04:13.522 15800 15800 D TestApp : *** BAD OBJECT: 0x989e93c8c0 ***
01-19 11:04:13.522 15800 15800 F TestApp : Runtime Error: /Users/ian/Downloads/TestApp/build/Android/Preview/app/src/main/jni/Uno/Memory.cpp:420: (no message)
01-19 11:04:13.522 15800 15800 I TestApp : MessageBox [Fatal Error]: The application has crashed.
01-19 11:04:13.522 15800 16145 D TestApp : someDate changed: "2007-02-08T00:00:00.000Z"
01-19 11:04:13.552 15800 15800 D ViewRootImpl: #1 mView = com.android.internal.policy.PhoneWindow$DecorView{827cb7c V.E...... R.....I. 0,0-0,0}
01-19 11:04:13.552   770  1777 D InputDispatcher: Focus left window: 15800
01-19 11:04:13.552   770  1777 D InputDispatcher: Focus entered window: 15800
01-19 11:04:21.372   770  1261 I InputDispatcher: Delivering touch to (15800): action: 0x0, toolType: 1
01-19 11:04:21.772   770  1261 I InputDispatcher: Delivering touch to (15800): action: 0x1, toolType: 1
01-19 11:04:21.872   770  1261 D InputDispatcher: Waiting for application to become ready for input: 15800.  Reason: Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago.  Wait queue length: 34.  Wait queue head age: 503.4ms.
```

Example source code (copying & pasting from https://www.fusetools.com/docs/fuse/controls/datepicker )
```
<StackPanel>
    <JavaScript>
        var Observable = require("FuseJS/Observable");

        var someDate = Observable(new Date(Date.parse("2007-02-14T00:00:00.000Z")));

        someDate.onValueChanged(module, function(date) {
            console.log("someDate changed: " + JSON.stringify(date));
        });

        module.exports = {
            someDate: someDate,

            minDate: new Date(Date.parse("1950-01-01T00:00:00.000Z")),
            maxDate: new Date(Date.parse("2050-01-01T00:00:00.000Z")),

            whoYouGonnaCall: function() {
                someDate.value = new Date(Date.parse("1984-06-08T00:00:00.000Z"));
            }
        };
    </JavaScript>

    <NativeViewHost>
        <DatePicker Value="{someDate}" MinValue="{minDate}" MaxValue="{maxDate}" />
    </NativeViewHost>

    <Button Text="Who you gonna call?" Clicked="{whoYouGonnaCall}" Margin="5" />
</StackPanel>
```

**Comment by kusma** [comment] 2018-01-19 09:10
This is a duplicate of #764.

**Closed by kusma** 2018-01-19 09:10 UTC
