### ISSUE TITLE
HEIF file support in Image

### ISSUE THREAD

**Issue by nekronos** [fusetools/fuselibs-public#682] opened 2017-11-03 10:26 UTC
iOS 11 adds a new file format for images, [HEIF](https://en.wikipedia.org/wiki/High_Efficiency_Image_File_Format). We currently do not support that in our `<Image />`.

**Comment by yupferris** [comment] 2017-11-03 10:32
Dupe of #668

**Closed by yupferris** 2017-11-03 10:32 UTC
Labels: Severity: Feature
