### ISSUE TITLE
Custom URI support in WebView

### ISSUE THREAD

**Issue by eksperts** [fusetools/fuselibs-public#792] opened 2017-11-23 11:34 UTC
[Reported on community](https://www.fusetools.com/community/forums/general/custom_uri_support_in_webview).

Copy-pasting the message:
_Hello! This issue has been discussed previously three months ago in the forums + Slack, and since there hasn't been an update (that i'm aware of) I'd like to bring this up again. Currently the WebView halts to an error page "web page not available" instead of passing the URI to an InterApp process and opening the corresponding external app. Because the WebView halts on this error, there's no way of getting the URI manually from the WebView since it's not presented in the Url. I found a dirty way of getting this URI (by stripping it from the WebView source) but it doesn't work on all Android devices because they use different browsers for the WebView.

Is there an update coming to this issue or can I use Foreign Code to rewrite shouldOverrideUrlLoading on WebView to process URI's?_

There seems to be [some work done](https://github.com/fusetools/fuselibs-public/pull/170) around this, but that PR was eventually rolled back since it caused some other issues.

How do we move forward with this? It's likely something that is very useful (or even critical) to handling somewhat advanced use cases.

**Comment by kusma** [comment] 2017-11-23 11:36
Duplicate of #345

**Closed by kusma** 2017-11-23 11:36 UTC
